from django.urls import path, include
from .views import (SignUpView, LoginView, RegenrateAccessToken, GetCurrentUserData, ForgotPasswordView,
                    ResetPasswordView, LogoutView, AddProductView, GetAllProducts, GetProduct, UpdateProduct, DeleteProduct,
                    SearchProduct, AddToCartView, GetCurrentUserCartView, RemoveProductFromCartView, UpdateProductQuantityView, 
                    ResetCartView, AddToWishList, GetCurrentUserWishListView, RemoveFromWishlist, ResetWishList,
                    AddDiscountTOProduct, CreateCategoryView, GetAllCategoriesView, DeleteProductCategory, GetSpecificProductCategory,
                    CreateSubCategoryView, GetAllSubCategoriesView, GetSpecificSubCategory, DeleteSubCategoryView, FilterProductsView)

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("get_current_user_data/", GetCurrentUserData.as_view(), name="regenerate-access-token"),
    path("regenerate_access_token/", RegenrateAccessToken.as_view(), name="regenerate-access-token"),
    path("forgot_password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset_password/", ResetPasswordView.as_view(), name="reset-password"),
    path("add_product/", AddProductView.as_view(), name="add-product"),
    path("add_discount_to_product/", AddDiscountTOProduct.as_view(), name="add-discount-to-product"),
    path("get_all_products/", GetAllProducts.as_view(), name="get-all-product"),
    path("get_product/<str:product_id>", GetProduct.as_view(), name="get-product"),
    path("update_product/<str:product_id>", UpdateProduct.as_view(), name="update-product"),
    path("delete_product/<str:product_id>", DeleteProduct.as_view(), name="delete-product"),
    path("search/", SearchProduct.as_view(), name="search-product"),
    path("add_to_cart/", AddToCartView.as_view(), name="add-to-cart"),
    path("get_user_cart/", GetCurrentUserCartView.as_view(), name="get-current-user-cart"),
    path("delete_from_cart/", RemoveProductFromCartView.as_view(), name="delete-from-user-cart"),
    path("update_quantity/", UpdateProductQuantityView.as_view(), name="update-quantity"),
    path("reset_cart/", ResetCartView.as_view(), name="reset-cart"),
    path("add_to_wishlist/", AddToWishList.as_view(), name="add-to-wishlist"),
    path("get_user_wishlist/", GetCurrentUserWishListView.as_view(), name="get-user-wishlist"),
    path("delete_from_wishlist/", RemoveFromWishlist.as_view(), name="delete-from-wishlist"),
    path("reset_wishlist/", ResetWishList.as_view(), name="reset-wishlist"),
    path("create_category/", CreateCategoryView.as_view(), name="create-category"),
    path("get_all_categories/", GetAllCategoriesView.as_view(), name="get-all-categories"),
    path("delete_category/", DeleteProductCategory.as_view(), name="get-all-categories"),
    path("get_category/<str:category_id>", GetSpecificProductCategory.as_view(), name="get-all-categories"),
    path("create_subCategory/", CreateSubCategoryView.as_view(), name="create-subCategory"),
    path("get_all_subCategories/", GetAllSubCategoriesView.as_view(), name="get-all-subCategories"),
    path("get_subCategory/<str:subCategory_id>", GetSpecificSubCategory.as_view(), name="get-subCategory"),
    path("delete_subCategory/", DeleteSubCategoryView.as_view(), name="delete-subCategory"),
    path("filter_products/", FilterProductsView.as_view(), name="filter-products"),
    path('chat/', include('api.chat.urls'))
]